#!/usr/bin/env python3
"""Retired legacy landing-page emitter.

The original script embedded promotional copy and could overwrite source-led,
manually reviewed service pages.  It remains as an explicit fail-closed tombstone
because older documentation and maintenance checks still reference this path.
No public page is generated by this module.
"""

from __future__ import annotations

from pathlib import Path


REPO = Path(__file__).resolve().parent

# Stable verified constants retained for repository contracts that audit public
# geo metadata and the canonical Person entity identifier.
VERIFIED_GEO_POSITION = "40.7157;-74.3601"
VERIFIED_ICBM = "40.7157, -74.3601"
VERIFIED_PERSON_ID = "https://thejorgeramirezgroup.com/#jorge-ramirez"

MANUALLY_MANAGED_ROUTES = frozenset(
    {
        "buyer-agency-agreement-nj",
        "cash-offer-nj",
        "divorce-home-sale-nj",
        "downsizing-nj",
        "inherited-home-nj",
        "investment-property-nj",
        "luxury-homes-nj",
        "nyc-to-nj-relocation",
        "relocating-from-nj",
        "sell-rental-property-nj",
    }
)

# Intentionally empty. Public routes above are maintained in their HTML source
# files and dedicated reviewed renderers, where applicable.
PAGES: dict[str, object] = {}


def main() -> None:
    """Abort before any file write, even if this legacy entry point is invoked."""

    raise RuntimeError(
        "generate_new_landing_pages.py is retired; all former outputs are "
        "manually managed source-led pages"
    )


if __name__ == "__main__":
    main()
