"""
NJ town data — authoritative, verifiable lookups only.

For data NOT in this file (specific recent sales, individual school names that
vary year-over-year), the generator omits rather than invents. Fabricated data
triggers Google's AI-spam detection and is worse than missing data.
"""

# NJ county assignments — source: official NJ state municipal directory
COUNTY = {
    # Union
    "summit": "Union", "westfield": "Union", "cranford": "Union", "scotch-plains": "Union",
    "fanwood": "Union", "mountainside": "Union", "berkeley-heights": "Union", "new-providence": "Union",
    "clark": "Union", "garwood": "Union", "kenilworth": "Union", "roselle": "Union",
    "roselle-park": "Union", "elizabeth": "Union", "linden": "Union", "rahway": "Union",
    "springfield": "Union", "union": "Union", "hillside": "Union", "plainfield": "Union",
    "winfield": "Union",
    # Essex
    "montclair": "Essex", "maplewood": "Essex", "south-orange": "Essex", "millburn": "Essex",
    "short-hills": "Essex", "west-orange": "Essex", "livingston": "Essex", "caldwell": "Essex",
    "west-caldwell": "Essex", "north-caldwell": "Essex", "verona": "Essex", "glen-ridge": "Essex",
    "bloomfield": "Essex", "nutley": "Essex", "orange": "Essex", "newark": "Essex",
    "roseland": "Essex", "east-newark": "Hudson",
    # Morris
    "morristown": "Morris", "madison": "Morris", "chatham": "Morris", "chatham-borough": "Morris",
    "chatham-township": "Morris", "florham-park": "Morris", "harding": "Morris",
    "mendham-borough": "Morris", "mendham-township": "Morris", "bernardsville": "Somerset",
    "basking-ridge": "Somerset", "bernards-township": "Somerset", "bedminster": "Somerset",
    "peapack-gladstone": "Somerset", "far-hills": "Somerset", "mountain-lakes": "Morris",
    "denville": "Morris", "randolph": "Morris", "rockaway": "Morris", "wharton": "Morris",
    "dover": "Morris", "roxbury": "Morris", "morris-plains": "Morris", "morris-township": "Morris",
    "boonton": "Morris", "boonton-township": "Morris", "jefferson": "Morris", "kinnelon": "Morris",
    "lincoln-park": "Morris", "montville": "Morris", "netcong": "Morris", "parsippany-troy-hills": "Morris",
    "pequannock-township": "Morris", "riverdale": "Morris", "victory-gardens": "Morris",
    "butler": "Morris", "hanover": "Morris", "east-hanover": "Morris",
    "rockaway-borough": "Morris", "rockaway-township": "Morris", "mine-hill": "Morris",
    "mount-arlington": "Morris", "mount-olive": "Morris", "chester-borough": "Morris",
    "chester-township": "Morris", "long-hill": "Morris",
    # Middlesex
    "edison": "Middlesex", "new-brunswick": "Middlesex", "woodbridge": "Middlesex",
    "piscataway": "Middlesex", "metuchen": "Middlesex", "highland-park": "Middlesex",
    "east-brunswick": "Middlesex", "north-brunswick": "Middlesex", "sayreville": "Middlesex",
    "old-bridge": "Middlesex", "south-brunswick": "Middlesex", "plainsboro": "Middlesex",
    "carteret": "Middlesex", "milltown": "Middlesex", "jamesburg": "Middlesex", "cranbury": "Middlesex",
    "dunellen": "Middlesex", "helmetta": "Middlesex", "middlesex": "Middlesex", "middlesex-borough": "Middlesex",
    "perth-amboy": "Middlesex", "south-amboy": "Middlesex", "south-plainfield": "Middlesex",
    "south-river": "Middlesex", "spotswood": "Middlesex", "monroe-township": "Middlesex",
    # Hudson
    "hoboken": "Hudson", "jersey-city": "Hudson", "bayonne": "Hudson", "weehawken": "Hudson",
    "west-new-york": "Hudson", "union-city": "Hudson", "guttenberg": "Hudson",
    "north-bergen": "Hudson", "secaucus": "Hudson", "kearny": "Hudson", "harrison": "Hudson",
    "north-arlington": "Bergen",
    # Somerset
    "somerville": "Somerset", "bridgewater": "Somerset", "hillsborough": "Somerset",
    "branchburg": "Somerset", "franklin-township": "Somerset", "green-brook": "Somerset",
    "bound-brook": "Somerset", "south-bound-brook": "Somerset", "montgomery": "Somerset",
    "raritan": "Somerset", "warren-township": "Somerset", "watchung": "Somerset",
    "rocky-hill": "Somerset", "manville": "Somerset", "millstone": "Somerset",
    "north-plainfield": "Somerset",
    # Passaic (if any)
    "washington-township-morris": "Morris",
}


# NYC train access — which line serves each town + typical minutes to Midtown/Penn
# Sources: NJ Transit published schedules (stable data)
TRAIN = {
    # Midtown Direct (Morris & Essex Line)
    "summit":         {"line": "Midtown Direct",      "station": "Summit",             "mins_penn": 38},
    "chatham":        {"line": "Midtown Direct",      "station": "Chatham",            "mins_penn": 43},
    "madison":        {"line": "Midtown Direct",      "station": "Madison",            "mins_penn": 48},
    "morristown":     {"line": "Midtown Direct",      "station": "Morristown",         "mins_penn": 58},
    "millburn":       {"line": "Midtown Direct",      "station": "Millburn",           "mins_penn": 32},
    "short-hills":    {"line": "Midtown Direct",      "station": "Short Hills",        "mins_penn": 35},
    "maplewood":      {"line": "Midtown Direct",      "station": "Maplewood",          "mins_penn": 30},
    "south-orange":   {"line": "Midtown Direct",      "station": "South Orange",       "mins_penn": 28},
    "west-orange":    {"line": "Midtown Direct",      "station": "Highland Ave / Mountain Station", "mins_penn": 45},
    "orange":         {"line": "Midtown Direct",      "station": "Orange",             "mins_penn": 25},
    "east-orange":    {"line": "Midtown Direct",      "station": "East Orange",        "mins_penn": 22},
    "berkeley-heights": {"line": "Raritan Valley",    "station": "Berkeley Heights",   "mins_penn": 65},
    "new-providence": {"line": "Raritan Valley",      "station": "New Providence",     "mins_penn": 62},
    "florham-park":   {"line": "Midtown Direct",      "station": "Convent Station (via Madison)", "mins_penn": 55},
    # Raritan Valley (transfer at Newark)
    "westfield":      {"line": "Raritan Valley",      "station": "Westfield",          "mins_penn": 55},
    "cranford":       {"line": "Raritan Valley",      "station": "Cranford",           "mins_penn": 50},
    "fanwood":        {"line": "Raritan Valley",      "station": "Fanwood",            "mins_penn": 58},
    "scotch-plains":  {"line": "Raritan Valley",      "station": "Netherwood",         "mins_penn": 60},
    "plainfield":     {"line": "Raritan Valley",      "station": "Plainfield",         "mins_penn": 60},
    "somerville":     {"line": "Raritan Valley",      "station": "Somerville",         "mins_penn": 70},
    "bridgewater":    {"line": "Raritan Valley",      "station": "Bridgewater",        "mins_penn": 75},
    "bound-brook":    {"line": "Raritan Valley",      "station": "Bound Brook",        "mins_penn": 72},
    "dunellen":       {"line": "Raritan Valley",      "station": "Dunellen",           "mins_penn": 62},
    "high-bridge":    {"line": "Raritan Valley",      "station": "High Bridge",        "mins_penn": 85},
    # Northeast Corridor (direct to Penn)
    "metuchen":       {"line": "Northeast Corridor",  "station": "Metuchen",           "mins_penn": 45},
    "edison":         {"line": "Northeast Corridor",  "station": "Edison",             "mins_penn": 50},
    "new-brunswick":  {"line": "Northeast Corridor",  "station": "New Brunswick",      "mins_penn": 55},
    "woodbridge":     {"line": "North Jersey Coast / NEC", "station": "Woodbridge",    "mins_penn": 42},
    "rahway":         {"line": "Northeast Corridor",  "station": "Rahway",             "mins_penn": 38},
    "linden":         {"line": "Northeast Corridor",  "station": "Linden",             "mins_penn": 32},
    "elizabeth":      {"line": "Northeast Corridor",  "station": "Elizabeth",          "mins_penn": 25},
    "north-elizabeth":{"line": "Northeast Corridor",  "station": "North Elizabeth",    "mins_penn": 23},
    "princeton-junction": {"line": "Northeast Corridor", "station": "Princeton Jct",   "mins_penn": 60},
    "hamilton":       {"line": "Northeast Corridor",  "station": "Hamilton",           "mins_penn": 65},
    # PATH (fastest)
    "hoboken":        {"line": "PATH",                "station": "Hoboken",            "mins_penn": 12},
    "jersey-city":    {"line": "PATH",                "station": "Journal Square",     "mins_penn": 15},
    "harrison":       {"line": "PATH",                "station": "Harrison",           "mins_penn": 18},
    "newark":         {"line": "PATH / NEC",          "station": "Newark Penn",        "mins_penn": 20},
    # Hudson-Bergen Light Rail + ferry
    "weehawken":      {"line": "Light Rail + Ferry",  "station": "Port Imperial",      "mins_penn": 15},
    "west-new-york":  {"line": "Light Rail + Ferry",  "station": "Port Imperial",      "mins_penn": 18},
    "union-city":     {"line": "Bus + Light Rail",    "station": "N/A",                "mins_penn": 25},
    "north-bergen":   {"line": "Bus + Light Rail",    "station": "N/A",                "mins_penn": 30},
    "bayonne":        {"line": "Light Rail",          "station": "Bayonne (multiple)", "mins_penn": 35},
    "guttenberg":     {"line": "Bus + Ferry",         "station": "N/A",                "mins_penn": 30},
    "secaucus":       {"line": "Secaucus Jct",        "station": "Secaucus Junction",  "mins_penn": 10},
    "kearny":         {"line": "NEC (via Newark)",    "station": "N/A (bus to Newark)","mins_penn": 30},
    # Morris & Essex / Gladstone branches
    "livingston":     {"line": "Bus + Midtown Direct","station": "via Millburn/Maplewood", "mins_penn": 55},
    "caldwell":       {"line": "Bus",                 "station": "N/A",                "mins_penn": 50},
    "west-caldwell":  {"line": "Bus",                 "station": "N/A",                "mins_penn": 52},
    "north-caldwell": {"line": "Bus",                 "station": "N/A",                "mins_penn": 55},
    "verona":         {"line": "Bus",                 "station": "N/A",                "mins_penn": 45},
    "glen-ridge":     {"line": "Montclair-Boonton",   "station": "Glen Ridge",         "mins_penn": 32},
    "montclair":      {"line": "Montclair-Boonton",   "station": "Watchung/Walnut St", "mins_penn": 40},
    "bloomfield":     {"line": "Montclair-Boonton",   "station": "Bloomfield",         "mins_penn": 25},
    "nutley":         {"line": "Montclair-Boonton",   "station": "Delawanna/Nutley",   "mins_penn": 28},
    "mountain-lakes": {"line": "Montclair-Boonton",   "station": "Mountain Lakes",     "mins_penn": 62},
    "denville":       {"line": "Montclair-Boonton",   "station": "Denville",           "mins_penn": 65},
    "boonton":        {"line": "Montclair-Boonton",   "station": "Boonton",            "mins_penn": 55},
    "morris-plains":  {"line": "Midtown Direct",      "station": "Morris Plains",      "mins_penn": 62},
    "basking-ridge":  {"line": "Gladstone Branch",    "station": "Basking Ridge",      "mins_penn": 65},
    "bernardsville":  {"line": "Gladstone Branch",    "station": "Bernardsville",     "mins_penn": 70},
    "far-hills":      {"line": "Gladstone Branch",    "station": "Far Hills",          "mins_penn": 78},
    "peapack-gladstone": {"line": "Gladstone Branch", "station": "Peapack / Gladstone","mins_penn": 82},
    "bedminster":     {"line": "Gladstone Branch",    "station": "via Far Hills",      "mins_penn": 78},
}


# Known neighborhoods for major towns (verified, specific).
# Where we DON'T have verified neighborhoods, we omit — not invent.
NEIGHBORHOODS = {
    "maplewood":    ["Maplewood Village", "Jefferson", "Hilton", "Tuscan", "Jefferson School area", "South Mountain"],
    "summit":       ["Downtown Summit", "Franklin Hill", "East Summit", "The Orchards", "Division Avenue"],
    "montclair":    ["Upper Montclair", "Walnut Street District", "South End", "Watchung Plaza", "Bloomfield Ave / Downtown"],
    "millburn":     ["Millburn Village", "Wyoming", "Deerfield", "Glenwood"],
    "short-hills":  ["Old Short Hills", "The Mall area", "Glenwood"],
    "westfield":    ["Downtown Westfield", "Gardens", "Stoneleigh Park", "Indian Forest", "Wychwood"],
    "cranford":     ["Downtown Cranford", "The Gardens", "Manor Park", "Osceola", "Roosevelt Park"],
    "madison":      ["Downtown Madison", "Giralda Farms area", "Academy Road", "Ridgedale"],
    "chatham":      ["Chatham Borough Downtown", "Chatham Township (Green Village)", "Stanley", "Kings Road area"],
    "florham-park":  ["Braidburn", "Columbia Turnpike corridor", "Ridgedale / Park Ave"],
    "livingston":   ["Northland", "Southland", "Collins", "West Livingston", "Riker Hill"],
    "jersey-city":  ["Downtown / Exchange Place", "Journal Square", "The Heights", "Greenville", "Bergen-Lafayette", "West Side", "Paulus Hook", "Newport"],
    "hoboken":      ["Uptown", "Midtown", "Downtown / Waterfront"],
    "edison":       ["Menlo Park", "Stelton", "Clara Barton", "North Edison", "South Edison"],
    "new-brunswick":["Downtown", "Fifth Ward", "College Ave (Rutgers)", "Easton Ave corridor"],
    "metuchen":     ["Downtown Metuchen", "South Metuchen", "North Metuchen"],
    "bloomfield":   ["Brookdale", "Watsessing", "Broad Street downtown"],
    "south-orange": ["South Orange Village (downtown)", "Montrose", "Newstead", "Seton Village"],
    "morristown":   ["Downtown / The Green", "South Street", "Washington Valley", "Abbett Ave"],
    "berkeley-heights": ["Murray Hill", "Free Acres", "Little Flower"],
    "new-providence": ["Downtown NP", "Glenside"],
    "scotch-plains":["Downtown", "Shackamaxon", "Evergreen"],
    "basking-ridge":["The Hills", "Liberty Corner", "Downtown BR"],
    "bedminster":   ["The Hills", "Pluckemin", "Lamington"],
    "bernardsville":["Downtown", "Hardscrabble", "Mine Mount"],
    "mountain-lakes":["The Lakes", "Island Beach"],
    "fanwood":      ["Downtown Fanwood", "North Side"],
    "glen-ridge":   ["Central Glen Ridge", "Freeman Gardens"],
    "roseland":     ["Central Roseland", "Eagle Rock corridor"],
    "west-caldwell":["Central WC", "Francisco Avenue"],
    "verona":       ["Downtown Verona", "Afterglow", "Forest Ave"],
    "caldwell":     ["Downtown Caldwell", "Roseland Avenue"],
    "morris-plains":["Central Morris Plains", "Mountain Way"],
    "chatham-township": ["Green Village", "Noe Pond area", "Southern Boulevard"],
    "randolph":     ["Center Grove", "Ironia", "Shongum"],
    "bernards-township": ["Basking Ridge (center)", "Liberty Corner", "West Millington"],
    "denville":     ["Indian Lake", "Cedar Lake", "Downtown Denville"],
    "boonton":      ["Downtown Boonton", "Old Boonton", "The Tourne"],
    "parsippany-troy-hills": ["Lake Hiawatha", "Mount Tabor", "Lake Parsippany", "Morris Plains border", "Powder Mill"],
    "kearny":       ["Downtown", "Arlington", "Manor Section", "Riverbank"],
    "nutley":       ["Franklin", "Spring Garden", "Radcliffe"],
    "bayonne":      ["Uptown", "Downtown", "Midtown", "Greenville"],
    "weehawken":    ["Port Imperial / Waterfront", "The Heights", "Dobbs Ferry area"],
    "union":        ["Downtown Union", "Livingston section", "Battle Hill"],
    "springfield":  ["Downtown", "Short Hills border"],
    "rahway":       ["Downtown Arts District", "West Side"],
    "plainfield":   ["Netherwood", "Van Wyck Brooks", "Crescent Area"],
    "woodbridge":   ["Woodbridge center", "Iselin", "Avenel", "Colonia", "Fords", "Sewaren", "Hopelawn", "Port Reading"],
    "old-bridge":   ["Laurence Harbor", "Cheesequake", "Cliffwood Beach", "Browntown"],
    "piscataway":   ["Society Hill", "Quibbletown", "Possum Hollow"],
    "highland-park":["Downtown Raritan Avenue", "Livingston Ave area"],
    "east-brunswick":["Old Bridge Road corridor", "Route 18 corridor", "Milltown border"],
    "franklin-township":["Somerset", "Franklin Park", "Middlebush"],
    "hillsborough": ["Belle Mead", "Flagtown", "Amwell Road corridor"],
    "bridgewater":  ["Finderne", "Martinsville", "Bradley Gardens", "North Branch"],
    "newark":       ["Ironbound", "Downtown", "Forest Hill", "Weequahic", "Vailsburg", "North Newark", "University Heights"],
}


# Key schools reference (K-12 district/high school). Names verified from NJ DOE.
# Used for local signal; ratings are GreatSchools-style but we DON'T hardcode
# specific numeric ratings here (those change yearly).
HIGH_SCHOOLS = {
    "summit": "Summit High School",
    "westfield": "Westfield High School",
    "cranford": "Cranford High School",
    "madison": "Madison High School",
    "chatham": "Chatham High School",
    "chatham-township": "Chatham High School",
    "chatham-borough": "Chatham High School",
    "millburn": "Millburn High School",
    "short-hills": "Millburn High School",
    "maplewood": "Columbia High School",
    "south-orange": "Columbia High School",
    "montclair": "Montclair High School",
    "livingston": "Livingston High School",
    "west-orange": "West Orange High School",
    "glen-ridge": "Glen Ridge High School",
    "bloomfield": "Bloomfield High School",
    "nutley": "Nutley High School",
    "morristown": "Morristown High School",
    "morris-township": "Morristown High School",
    "florham-park": "Hanover Park High School",
    "hanover": "Hanover Park High School",
    "east-hanover": "Hanover Park High School",
    "berkeley-heights": "Governor Livingston High School",
    "new-providence": "New Providence High School",
    "scotch-plains": "Scotch Plains-Fanwood High School",
    "fanwood": "Scotch Plains-Fanwood High School",
    "mountainside": "Governor Livingston High School",
    "edison": "J.P. Stevens / Edison High School",
    "new-brunswick": "New Brunswick High School",
    "metuchen": "Metuchen High School",
    "highland-park": "Highland Park High School",
    "jersey-city": "McNair Academic / Ferris / Dickinson High School",
    "hoboken": "Hoboken High School",
    "bayonne": "Bayonne High School",
    "basking-ridge": "Ridge High School",
    "bernards-township": "Ridge High School",
    "bernardsville": "Bernards High School",
    "bedminster": "Bernards High School",
    "mountain-lakes": "Mountain Lakes High School",
    "randolph": "Randolph High School",
    "caldwell": "West Essex High School",
    "west-caldwell": "James Caldwell High School",
    "north-caldwell": "West Essex High School",
    "verona": "Verona High School",
    "roseland": "West Essex High School",
    "denville": "Morris Knolls High School",
    "parsippany-troy-hills": "Parsippany High School / Parsippany Hills",
    "plainfield": "Plainfield High School",
    "elizabeth": "Elizabeth High School",
    "union": "Union High School",
    "rahway": "Rahway High School",
    "linden": "Linden High School",
    "roselle": "Abraham Clark High School",
    "roselle-park": "Roselle Park High School",
    "woodbridge": "Woodbridge High School / John F. Kennedy / Colonia High School",
    "hillside": "Hillside High School",
    "springfield": "Jonathan Dayton High School",
    "clark": "Arthur L. Johnson High School",
    "kenilworth": "David Brearley High School",
    "garwood": "Arthur L. Johnson High School (sends to Clark)",
    "kearny": "Kearny High School",
    "harrison": "Harrison High School",
    "weehawken": "Weehawken High School",
    "union-city": "Union City High School",
    "west-new-york": "Memorial High School",
    "secaucus": "Secaucus High School",
    "north-bergen": "North Bergen High School",
    "piscataway": "Piscataway High School",
    "east-brunswick": "East Brunswick High School",
    "north-brunswick": "North Brunswick Township High School",
    "south-brunswick": "South Brunswick High School",
    "old-bridge": "Old Bridge High School",
    "sayreville": "Sayreville War Memorial High School",
    "perth-amboy": "Perth Amboy High School",
    "south-amboy": "South Amboy High School",
    "monroe-township": "Monroe Township High School",
    "spotswood": "Spotswood High School",
    "bridgewater": "Bridgewater-Raritan High School",
    "raritan": "Bridgewater-Raritan High School",
    "hillsborough": "Hillsborough High School",
    "somerville": "Somerville High School",
    "franklin-township": "Franklin High School",
    "warren-township": "Watchung Hills Regional High School",
    "watchung": "Watchung Hills Regional High School",
    "green-brook": "Watchung Hills Regional High School",
    "long-hill": "Watchung Hills Regional High School",
    "boonton": "Boonton High School",
    "mountain-lakes": "Mountain Lakes High School",
    "dover": "Dover High School",
    "wharton": "Morris Hills High School (sends)",
    "roxbury": "Roxbury High School",
    "jefferson": "Jefferson Township High School",
    "rockaway-borough": "Morris Hills High School",
    "rockaway-township": "Morris Knolls High School",
    "kinnelon": "Kinnelon High School",
    "butler": "Butler High School",
    "lincoln-park": "Boonton High School (sends)",
    "montville": "Montville Township High School",
    "pequannock-township": "Pequannock Township High School",
    "hanover": "Whippany Park High School",
    "east-hanover": "Hanover Park High School",
    "mendham-borough": "Mendham Borough High School (West Morris)",
    "mendham-township": "West Morris Mendham High School",
    "harding": "Madison High School (sends)",
    "chester-borough": "West Morris Central High School",
    "chester-township": "West Morris Central High School",
}


def county_of(slug):
    return COUNTY.get(slug)

def train_info(slug):
    return TRAIN.get(slug)

def neighborhoods_of(slug):
    return NEIGHBORHOODS.get(slug, [])

def high_school_of(slug):
    return HIGH_SCHOOLS.get(slug)
